### ISSUE TITLE
error when running semiAutomaticK.py

### ISSUE THREAD

**Issue by lixin4306ren** [phoenixding/scdiff#3]
Traceback (most recent call last):
  File "semiAutomaticK.py", line 9, in <module>
    colors_list = list(colors._colors_full_map.values())
AttributeError: 'module' object has no attribute '_colors_full_map'

**Comment by phoenixding** [comment]
@lixin4306ren 
Thanks for reporting this error.
In the recent  upgrade (>=matplotlib 3.0.2),  matplotlib removed this attribute ("_colors_full_map") for the matplotlib.colors module.   Therefore, the scripts can't find the color codes. 

I just fixed this in the most recent update.  You can try the updated semiAutomaticK.py script. 
Let me know if the problem persists, Thanks.

**Comment by lixin4306ren** [comment]
Thanks. Still got following error. However, I updated my python to python3 and reinstall the scdiff using pip3, the problem was solved.

/share/apps/anaconda3/lib/python2.7/site-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
Traceback (most recent call last):
  File "/share/home/xianghui02/lixin/soft/scdiff/semiAutomaticK.py", line 10, in <module>
    colors_list=list(colors.CSS4_COLORS.values())
AttributeError: 'module' object has no attribute 'CSS4_COLORS'

**Comment by phoenixding** [comment]
@lixin4306ren 
I believe that the problem was caused by the matplotlib version.
This property ("CSS4_COLORS") might be missing from matplotlib.colors modules in some versions. 

I'll specify the required matplotlib version in the readme.  Thanks for reporting this error.
