### ISSUE TITLE
compatibility issue on newer version of pydiffmap package (0.2.0)

### ISSUE THREAD

**Issue by hmkim93** [phoenixding/scdiff#6]
Looks like there is a compatibility issue with pydiffmap pakage.

Installing scdiff from PyPI installs pydiffmap==0.2.0
arguments for pydiffmap.diffusion_map.DiffusionMap in this version has changed, and gives error when executed.

uninstalling pydiffmap and reinstalling "pydiffmap<0.2.0" resolved the error.

**Comment by phoenixding** [comment]
@hmkim93 
Thank you so much for reporting this error.
I will update the installation instructions accordingly. 
Sorry for any inconvenience it may cause to you.

**Comment by hmkim93** [comment]
Thank you!
